spring.application.name=assetflow-gateway
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=5
spring.cloud.gateway.discovery.locator.enabled=false
app.jwt.secret=${APP_JWT_SECRET:assetflow_secret_key_2025_assetflow_secret_key_2025_secure}
