import { useState } from 'react';
import { FaDownload, FaChartBar, FaPrint } from 'react-icons/fa';
import { getReport } from '../../services/notificationService';
import { exportCsv, exportPdf, exportXlsx, printRows } from '../../utils/export';

const reportTypes = [['assets','Assets'],['users','Users'],['maintenance','Maintenance'],['purchase-orders','Purchase orders']];
export default function Reports(){
  const [type,setType]=useState('assets'); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const load=async(next=type)=>{setType(next);setLoading(true);setError('');try{setRows(await getReport(next)||[])}catch(e){setError(e.response?.data?.message||'Unable to load report.')}finally{setLoading(false)}};
  return <div><div className="page-heading d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div className="eyebrow">Operational intelligence</div><h1>Reports</h1><p>Live, tenant-scoped summaries from the notification and audit service.</p></div><div className="d-flex flex-wrap gap-2"><button className="btn btn-ghost" disabled={!rows.length} onClick={()=>exportCsv(`${type}-report`,rows)}><FaDownload className="me-2"/>CSV</button><button className="btn btn-ghost" disabled={!rows.length} onClick={()=>exportXlsx(`${type}-report`,rows)}>Excel</button><button className="btn btn-ghost" disabled={!rows.length} onClick={()=>exportPdf(`${type}-report`,rows)}>PDF</button><button className="btn btn-ghost" disabled={!rows.length} onClick={()=>printRows(`${type}-report`,rows)}><FaPrint className="me-2"/>Print</button></div></div><div className="surface p-4"><div className="d-flex flex-wrap gap-2 mb-4">{reportTypes.map(([key,label])=><button key={key} className={`btn ${type===key?'btn-primary':'btn-ghost'}`} onClick={()=>load(key)}><FaChartBar className="me-2"/>{label}</button>)}</div>{error&&<div className="alert alert-danger">{error}</div>}{loading?<div className="py-5 text-center"><div className="spinner-border text-primary"/></div>:!rows.length?<div className="empty-state"><h5>No report data yet</h5><p className="muted">Choose a report after your workspace has recorded activity.</p><button className="btn btn-primary" onClick={()=>load(type)}>Load report</button></div>:<div className="table-responsive"><table className="table workspace-table"><thead><tr>{Object.keys(rows[0]).map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{Object.values(row).map((v,j)=><td key={j}>{String(v??'—')}</td>)}</tr>)}</tbody></table></div>}</div></div>}
