spring.application.name=assetflow-auth-service
server.port=${SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/assetflow_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Astrixz}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

app.jwt.secret=${APP_JWT_SECRET:assetflow_secret_key_2025_assetflow_secret_key_2025_secure}
app.jwt.access-minutes=${APP_JWT_ACCESS_MINUTES:60}
app.jwt.refresh-days=${APP_JWT_REFRESH_DAYS:7}

logging.level.org.springframework.security=${LOG_LEVEL_SECURITY:INFO}
