import { Link } from 'react-router-dom';
import { FaArrowRight, FaBoxes, FaChartLine, FaCheck, FaClipboardCheck, FaClock, FaCogs, FaLock, FaRobot, FaShieldAlt, FaUsers } from 'react-icons/fa';

const features = [
  ['Lifecycle control', 'Track every purchase, assignment, transfer, repair, return, and disposal event in one auditable timeline.', FaBoxes],
  ['Tenant-safe by design', 'Role-based access and company-scoped queries keep every workspace isolated from the next.', FaLock],
  ['Operations intelligence', 'See utilization, warranty exposure, maintenance workload, and inventory health at a glance.', FaChartLine],
  ['Built for people', 'Employees get a simple self-service portal while admins keep approvals and policy controls.', FaUsers],
];

const steps = [
  ['01', 'Connect your workspace', 'Register a company, invite your team, and establish departments and locations.'],
  ['02', 'Build your inventory', 'Capture vendors, categories, purchase records, warranties, and asset identifiers.'],
  ['03', 'Run the lifecycle', 'Allocate, transfer, maintain, return, and retire assets with an audit trail at every step.'],
];

export default function Home() {
  return <main>
    <section className="hero py-5">
      <div className="container py-lg-5"><div className="row align-items-center g-5">
        <div className="col-lg-7"><span className="eyebrow">Asset operations, finally in one place</span><h1 className="mt-3">Make every asset accountable.</h1><p className="hero-lead mt-4">AssetFlow gives growing teams a secure, beautifully simple system for managing the complete journey from purchase to disposal.</p><div className="d-flex gap-3 flex-wrap mt-4"><Link className="btn btn-primary btn-lg" to="/register-company">Start your workspace <FaArrowRight className="ms-2"/></Link><Link className="btn btn-outline-primary btn-lg" to="/pricing">Explore plans</Link></div><div className="d-flex flex-wrap gap-4 mt-4 small muted"><span><FaCheck className="text-success me-2"/>Multi-tenant isolation</span><span><FaCheck className="text-success me-2"/>JWT-secured access</span><span><FaCheck className="text-success me-2"/>Export-ready reports</span></div></div>
        <div className="col-lg-5"><div className="hero-panel p-4"><div className="d-flex justify-content-between align-items-center mb-4"><span className="fw-bold">Operations overview</span><span className="badge text-bg-success">Live workspace</span></div><div className="mini-card mb-3"><small className="text-white-50">Asset utilization</small><div className="display-font fs-1 fw-bold">84.6%</div><small className="text-success"><FaChartLine className="me-1"/> +12.4% this quarter</small></div><div className="row g-3"><div className="col-6"><div className="mini-card"><small className="text-white-50">Active assets</small><div className="fs-3 fw-bold">1,248</div></div></div><div className="col-6"><div className="mini-card"><small className="text-white-50">Open requests</small><div className="fs-3 fw-bold">32</div></div></div></div><div className="mt-4 p-3 rounded-3" style={{background:'rgba(255,255,255,.08)'}}><div className="d-flex gap-2 align-items-center"><FaShieldAlt className="text-success"/><small>Audit trail and tenant controls active</small></div></div></div></div>
      </div></div>
    </section>

    <section className="section bg-surface"><div className="container"><div className="section-intro"><span className="eyebrow">One operating system for assets</span><h2 className="mt-2">From procurement to retirement, nothing gets lost.</h2><p className="muted mt-3">Replace spreadsheets and disconnected approvals with a shared source of truth your whole organization can trust.</p></div><div className="row g-4">{features.map(([title, text, Icon]) => <div className="col-md-6 col-xl-3" key={title}><article className="feature-card h-100"><div className="feature-icon mb-4"><Icon/></div><h5>{title}</h5><p className="muted mb-0">{text}</p></article></div>)}</div></div></section>

    <section className="section"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-5"><span className="eyebrow">A workflow that matches reality</span><h2 className="mt-2">Simple for employees. Powerful for operations.</h2><p className="muted mt-3">Give each role exactly the context and control it needs, without compromising security or visibility.</p><Link className="btn btn-primary mt-3" to="/about">See how AssetFlow works <FaArrowRight className="ms-2"/></Link></div><div className="col-lg-7"><div className="d-grid gap-3">{steps.map(([num, title, text]) => <div className="surface p-4 d-flex gap-4 align-items-start" key={num}><div className="stat-icon flex-shrink-0">{num}</div><div><h5 className="mb-1">{title}</h5><p className="muted mb-0">{text}</p></div></div>)}</div></div></div></div></section>

    <section className="section bg-surface"><div className="container"><div className="row g-4"><div className="col-lg-7"><div className="surface p-4 p-lg-5 h-100"><div className="d-flex align-items-center gap-3"><div className="feature-icon"><FaRobot/></div><div><span className="eyebrow">AssetFlow intelligence</span><h3 className="mt-1 mb-0">Ask your inventory questions in plain English.</h3></div></div><p className="muted mt-4">Use the AI assistant to summarize your workspace, surface maintenance priorities, explain reports, and find operational insights. It remains useful even when an external provider is unavailable.</p><div className="d-flex flex-wrap gap-2 mt-4"><span className="badge rounded-pill text-bg-light">Warranty exposure</span><span className="badge rounded-pill text-bg-light">Utilization trends</span><span className="badge rounded-pill text-bg-light">Maintenance priorities</span></div></div></div><div className="col-lg-5"><div className="surface p-4 p-lg-5 h-100"><span className="eyebrow">Built for confidence</span><h3 className="mt-2">Controls that scale with your business.</h3><div className="d-grid gap-3 mt-4"><div className="d-flex gap-3"><FaCogs className="text-primary mt-1"/><span><strong>Role-aware workflows</strong><small className="d-block muted">Approvals and actions follow policy.</small></span></div><div className="d-flex gap-3"><FaClipboardCheck className="text-primary mt-1"/><span><strong>Complete auditability</strong><small className="d-block muted">Every business event is recorded.</small></span></div><div className="d-flex gap-3"><FaClock className="text-primary mt-1"/><span><strong>Faster decisions</strong><small className="d-block muted">Live dashboards replace manual chasing.</small></span></div></div></div></div></div></div></section>

    <section className="section"><div className="container"><div className="surface p-5 text-center" style={{background:'linear-gradient(135deg,var(--brand-dark),var(--brand))',color:'#fff'}}><h2 className="text-white">Ready to put your assets to work?</h2><p className="mt-3 mb-4" style={{color:'rgba(255,255,255,.78)'}}>Start with a secure workspace and grow into a complete operating system for your organization.</p><Link className="btn btn-light btn-lg" to="/register-company">Create your company <FaArrowRight className="ms-2"/></Link></div></div></section>

    <section className="section pt-0"><div className="container"><div className="section-intro"><span className="eyebrow">Questions, answered</span><h2 className="mt-2">A better way to manage the basics.</h2></div><div className="accordion" id="assetflowFaq"><div className="accordion-item"><h2 className="accordion-header"><button className="accordion-button" data-bs-toggle="collapse" data-bs-target="#faq-one">How does AssetFlow protect tenant data?</button></h2><div id="faq-one" className="accordion-collapse collapse show" data-bs-parent="#assetflowFaq"><div className="accordion-body muted">Every business record carries a company scope, and service-layer authorization checks ownership before reads, updates, and deletes.</div></div></div><div className="accordion-item"><h2 className="accordion-header"><button className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#faq-two">Can employees manage their own requests?</button></h2><div id="faq-two" className="accordion-collapse collapse" data-bs-parent="#assetflowFaq"><div className="accordion-body muted">Yes. Employees can request, return, and report issues while administrators control approvals and allocations.</div></div></div><div className="accordion-item"><h2 className="accordion-header"><button className="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#faq-three">What happens if AI or email is not configured?</button></h2><div id="faq-three" className="accordion-collapse collapse" data-bs-parent="#assetflowFaq"><div className="accordion-body muted">Core asset operations continue normally. AI returns a clear fallback response and email remains ready for deployment configuration.</div></div></div></div></div></section>
  </main>;
}
