-- Reset approved AssetFlow data while preserving only the platform owner.
USE assetflow_db;
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE ai_chat_history;
TRUNCATE TABLE password_reset_tokens;
TRUNCATE TABLE audit_logs;
TRUNCATE TABLE notifications;
TRUNCATE TABLE repair_history;
TRUNCATE TABLE asset_returns;
TRUNCATE TABLE asset_transfers;
TRUNCATE TABLE maintenance;
TRUNCATE TABLE asset_requests;
TRUNCATE TABLE asset_allocations;
TRUNCATE TABLE assets;
TRUNCATE TABLE purchase_orders;
TRUNCATE TABLE locations;
TRUNCATE TABLE vendors;
TRUNCATE TABLE asset_categories;
TRUNCATE TABLE departments;
DELETE FROM users WHERE role_id <> (SELECT role_id FROM roles WHERE role_name='SUPER_ADMIN');
DELETE FROM companies;
SET FOREIGN_KEY_CHECKS=1;
