package com.assetflow.notification.service;
import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.client.RestClient;
@Service public class NotificationDataService {private final JdbcTemplate db; private final String geminiKey; private final String geminiModel; public NotificationDataService(JdbcTemplate d,@Value("${app.gemini.api-key:}")String k,@Value("${app.gemini.model:gemini-2.0-flash}")String m){db=d;geminiKey=k;geminiModel=m;} private long number(Object value){if(value instanceof Number n)return n.longValue();return Long.parseLong(String.valueOf(value));} private long company(Map<String,Object> c){return number(c.get("companyId"));} private long user(Map<String,Object> c){return number(c.get("sub"));}
 public List<Map<String,Object>> notifications(Map<String,Object> c){return db.queryForList("select * from notifications where company_id=? and (user_id=? or user_id=0) order by created_at desc",company(c),user(c));}
 @Transactional public Map<String,Object> createNotification(Map<String,Object> c,Map<String,Object>b){db.update("insert into notifications(company_id,user_id,title,message) values(?,?,?,?)",company(c),b.getOrDefault("userId",user(c)),b.get("title"),b.get("message"));return b;}
 public void read(Map<String,Object> c,long id){db.update("update notifications set is_read=true where notification_id=? and company_id=?",id,company(c));}
 public List<Map<String,Object>> audits(Map<String,Object> c){return db.queryForList("select * from audit_logs where company_id=? order by created_at desc limit 200",company(c));}
 @Transactional public Map<String,Object> audit(Map<String,Object> c,Map<String,Object>b){db.update("insert into audit_logs(company_id,user_id,module,action,entity_id,description,ip_address) values(?,?,?,?,?,?,?)",company(c),user(c),b.get("module"),b.get("action"),b.get("entityId"),b.get("description"),b.get("ipAddress"));return b;}
 public Map<String,Object> dashboard(Map<String,Object> c){Map<String,Object> d=new LinkedHashMap<>();d.put("notifications",db.queryForObject("select count(*) from notifications where company_id=?",Long.class,company(c)));d.put("unreadNotifications",db.queryForObject("select count(*) from notifications where company_id=? and is_read=false",Long.class,company(c)));d.put("auditEvents",db.queryForObject("select count(*) from audit_logs where company_id=?",Long.class,company(c)));return d;}
 public List<Map<String,Object>> report(String type,Map<String,Object> c){String sql=switch(type){case"assets"->"select status,count(*) total from assets where company_id=? group by status";case"users"->"select role_id,count(*) total from users where company_id=? group by role_id";case"maintenance"->"select status,count(*) total from service_tickets where company_id=? group by status";default->"select status,count(*) total from purchase_orders where company_id=? group by status";};return db.queryForList(sql,company(c));}
 public Map<String,Object> chat(Map<String,Object> body){String prompt=String.valueOf(body.getOrDefault("message",""));if(geminiKey==null||geminiKey.isBlank())return Map.of("reply","Gemini is not configured yet. Set GEMINI_API_KEY in the notification service environment to enable company-aware answers.","configured",false);Map<String,Object> payload=Map.of("contents",List.of(Map.of("parts",List.of(Map.of("text",prompt)))));try{Map<?,?> result=RestClient.create().post().uri("https://generativelanguage.googleapis.com/v1beta/models/"+geminiModel+":generateContent?key="+geminiKey).body(payload).retrieve().body(Map.class);return Map.of("reply",result,"configured",true);}catch(Exception ex){return Map.of("reply","Gemini is configured but unavailable. Verify the key, model access, and network connection.","configured",true,"providerError",true);}}
}
